'use client';

import { FC, useState } from 'react';
import { SubmitHandler } from 'react-hook-form';
import Link from '@/components/ui/link';
import PinInput from '@/components/form/PinInput';

const TwoFactorAuth: FC = () => {
  const [hasExpired, setHasExpired] = useState(false);
  //   const onSubmit: SubmitHandler<SignInFormFields> = async data => {
  //     return new Promise(resolve => {
  //       console.log('form data', data);
  //       setTimeout(() => {
  //         resolve(true);
  //       }, 2000);
  //     });
  //   };

  return (
    <>
      <div className="mx-auto flex flex-col w-full justify-center space-y-6 sm:w-[350px] text-primary dark:text-white">
        <div className="flex flex-col space-y-2 text-center">
          <h1 className="text-2xl font-semibold">Verify your identity</h1>
          <p className="text-sm text-muted-foreground px-10">
            Enter the 6-digit code generated by your authenticator app.
          </p>
        </div>
        <div className="grid gap-6">
          <PinInput length={6} />
        </div>
      </div>
    </>
  );
};

export default TwoFactorAuth;
